# Generated by Django 5.2.7 on 2025-10-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ratingaggregate_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='chef_special',
            field=models.BooleanField(default=False),
        ),
    ]
