# Generated by Django 5.2.7 on 2025-10-25 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dish_chef_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='dish_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm'])]),
        ),
    ]
