# Generated by Django 5.2.7 on 2025-10-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_discount_flat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
